### PR TITLE
[Neighborhood-methods] Added the "Local Clustering coefficient for dir…

### PR DESCRIPTION
**Pull request by samk3211**
…ected graphs" example

### CODE REVIEW

**Comment by vasia** [comment]
Hi @samk3211!
This looks good ^^
Can you (1) clean up some debug comments you have and (2) add a couple of tests?
Then, we can merge this. Thanks!

**Comment by samk3211** [comment]
sure! :)

**Comment by vasia** [comment]
test-slack-channel...

**Comment by vasia** [comment]
ignore this comment ;)

**Comment by samk3211** [comment]
Done!

**Pull request merged**
